# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin_definitions.xdc

# Block Designs: bd/microblaze/microblaze.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze || ORIG_REF_NAME==microblaze} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_microblaze_0_3/microblaze_microblaze_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_3 || ORIG_REF_NAME==microblaze_microblaze_0_3} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_dlmb_v10_2/microblaze_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_dlmb_v10_2 || ORIG_REF_NAME==microblaze_dlmb_v10_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_ilmb_v10_2/microblaze_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_ilmb_v10_2 || ORIG_REF_NAME==microblaze_ilmb_v10_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_dlmb_bram_if_cntlr_2/microblaze_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==microblaze_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_ilmb_bram_if_cntlr_2/microblaze_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==microblaze_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_lmb_bram_2/microblaze_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_lmb_bram_2 || ORIG_REF_NAME==microblaze_lmb_bram_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_periph_imp_xbar_2/microblaze_microblaze_0_axi_periph_imp_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_periph_imp_xbar_2 || ORIG_REF_NAME==microblaze_microblaze_0_axi_periph_imp_xbar_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_periph_2/microblaze_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_periph_2 || ORIG_REF_NAME==microblaze_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_microblaze_0_axi_intc_2/microblaze_microblaze_0_axi_intc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_axi_intc_2 || ORIG_REF_NAME==microblaze_microblaze_0_axi_intc_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_microblaze_0_xlconcat_2/microblaze_microblaze_0_xlconcat_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_microblaze_0_xlconcat_2 || ORIG_REF_NAME==microblaze_microblaze_0_xlconcat_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_mdm_1_2/microblaze_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_mdm_1_2 || ORIG_REF_NAME==microblaze_mdm_1_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_clk_wiz_1_2/microblaze_clk_wiz_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_clk_wiz_1_2 || ORIG_REF_NAME==microblaze_clk_wiz_1_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_rst_clk_wiz_1_100M_2/microblaze_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==microblaze_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_axi_gpio_0_1/microblaze_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_axi_gpio_0_1 || ORIG_REF_NAME==microblaze_axi_gpio_0_1} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_axi_uartlite_0_1/microblaze_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_axi_uartlite_0_1 || ORIG_REF_NAME==microblaze_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_axi_quad_spi_0_1/microblaze_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_axi_quad_spi_0_1 || ORIG_REF_NAME==microblaze_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_axi_iic_0_0/microblaze_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze_axi_iic_0_0 || ORIG_REF_NAME==microblaze_axi_iic_0_0} -quiet] -quiet

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/VIVADO_PROJECTS/XC7A100T_Microblaze/XC7A100T_Microblaze.gen/sources_1/bd/microblaze/microblaze_ooc.xdc
