# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ck/Desktop/Workspace/FPGA_Workspace/VIVADO_PROJECTS/XC7A100T_Microblaze/XC7A100T_Microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_periph_imp_auto_ds_1/microblaze_microblaze_0_axi_periph_imp_auto_ds_1.xci
# IP: The module: 'microblaze_microblaze_0_axi_periph_imp_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/VIVADO_PROJECTS/XC7A100T_Microblaze/XC7A100T_Microblaze.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_periph_imp_auto_ds_1/microblaze_microblaze_0_axi_periph_imp_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_axi_periph_imp_auto_ds_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/VIVADO_PROJECTS/XC7A100T_Microblaze/XC7A100T_Microblaze.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_periph_imp_auto_ds_1/microblaze_microblaze_0_axi_periph_imp_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_axi_periph_imp_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ck/Desktop/Workspace/FPGA_Workspace/VIVADO_PROJECTS/XC7A100T_Microblaze/XC7A100T_Microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_periph_imp_auto_ds_1/microblaze_microblaze_0_axi_periph_imp_auto_ds_1.xci
# IP: The module: 'microblaze_microblaze_0_axi_periph_imp_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/VIVADO_PROJECTS/XC7A100T_Microblaze/XC7A100T_Microblaze.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_periph_imp_auto_ds_1/microblaze_microblaze_0_axi_periph_imp_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_axi_periph_imp_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ck/Desktop/Workspace/FPGA_Workspace/VIVADO_PROJECTS/XC7A100T_Microblaze/XC7A100T_Microblaze.gen/sources_1/bd/microblaze/ip/microblaze_microblaze_0_axi_periph_imp_auto_ds_1/microblaze_microblaze_0_axi_periph_imp_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_axi_periph_imp_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
